{
    search(query: "$query", type:ISSUE, first: 80, after: $cursor) {
      pageInfo {
          endCursor
          hasNextPage
      }
      edges {
          cursor
          node {
            ... on PullRequest {
                author {
                    __typename
                    login
                }
                assignees (last: 5) {
                  nodes {
                    __typename
                    login
                  }
                }
                reviewRequests (last: 5) {
                    nodes {
                        requestedReviewer {
                            ... on User {
                                __typename
                              login
                            }
                        }
                    }
                }
                baseRefName
                headRefName
                body
                bodyText
                closed
                closedAt
                createdAt
                id
                isDraft
                lastEditedAt
                locked
                mergeable
                merged
                mergedAt
                state
                title
                updatedAt
                url
                timelineItems (last:5) {
                    nodes {
                        __typename
                        ... on PullRequestCommit {
                            commit {
                                committer {
                                  name
                                  email
                                  date
                                }
                                commitUrl
                                committedDate
                                id
                                message
                                messageBody
                                pushedDate
                                url
                                zipballUrl
                            }
                            url
                        }
                        ... on IssueComment {
                            author {
                                ... on User {
                                    __typename
                                    login
                                }
                            }
                            publishedAt
                        }
                        ... on PullRequestReview {
                            author {
                                __typename
                                login
                            }
                            createdAt
                        }
                        ... on MergedEvent {
                            actor {
                                __typename
                                login
                            }
                            createdAt
                        }
                    }
                }
            }
          }
      }
    }
}