{
    search(query: "$query", type:ISSUE, first: 50, after: $cursor) {
      pageInfo {
          endCursor
          hasNextPage
      }
      edges {
          cursor
          node {
            ... on PullRequest {
                author {
                  __typename
                  ... on User {
                    login
                  }
                }
                assignees (last: 5) {
                  nodes {
                    __typename
                    ... on User {
                      login
                    }
                  }
                }
                reviewRequests (last: 5) {
                    nodes {
                        requestedReviewer {
                            __typename
                            ... on User {
                              login
                            }
                        }
                    }
                }
                baseRefName
                headRefName
                body
                bodyText
                closed
                closedAt
                createdAt
                id
                isDraft
                lastEditedAt
                locked
                mergeable
                merged
                mergedAt
                state
                title
                updatedAt
                url
                timelineItems (last:15 itemTypes:[ISSUE_COMMENT,PULL_REQUEST_COMMIT,MERGED_EVENT,PULL_REQUEST_COMMIT_COMMENT_THREAD,PULL_REQUEST_REVIEW_THREAD,PULL_REQUEST_REVIEW,REOPENED_EVENT,CLOSED_EVENT,ASSIGNED_EVENT,MENTIONED_EVENT]) {
                    nodes {
                        __typename
                        ... on PullRequestCommit {
                            commit {
                                committer {
                                  name
                                  email
                                  date
                                  user {
                                    __typename
                                    ... on User {
                                      login
                                    }
                                  }
                                }
                                commitUrl
                                committedDate
                                id
                                message
                                messageBody
                                pushedDate
                                url
                                zipballUrl
                            }
                            url
                        }
                        ... on IssueComment {
                            author {
                                __typename
                                ... on User {
                                    login
                                }
                            }
                            publishedAt
                        }
                        ... on PullRequestReview {
                            author {
                                __typename
                                ... on User {
                                    login
                                }
                            }
                            createdAt
                        }
                        ... on MergedEvent {
                            actor {
                                __typename
                                ... on User {
                                  login
                                }
                            }
                            createdAt
                        }
                    }
                }
            }
          }
       }
    }
}