apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    name: birdview
  name: birdview
  namespace: birdview
spec:
  minReadySeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: birdview
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        name: birdview
    spec:
      containers:
        - args: []
          env: []
          image: black32167/birdview
          imagePullPolicy: IfNotPresent
          name: birdview
          ports:
            - containerPort: 8888
              name: port
          stdin: false
          tty: false
          volumeMounts:
            - mountPath: "/config"
              name: config
      imagePullSecrets: []
      initContainers: []
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-birdview